# Generated by Django 3.2.13 on 2023-07-14 12:14

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('텃밭', '텃밭'), ('화단', '화단'), ('한달살기', '한달살기'), ('댕댕이', '댕댕이'), ('냥냥이', '냥냥이'), ('귀촌', '귀촌'), ('풍경', '풍경'), ('축제', '축제'), ('명소', '명소'), ('자유', '자유')], max_length=10)),
                ('region', models.CharField(choices=[('강원도', '강원도'), ('경기도', '경기도'), ('경상남도', '경상남도'), ('경상북도', '경상북도'), ('광주광역시', '광주광역시'), ('대구광역시', '대구광역시'), ('대전광역시', '대전광역시'), ('부산광역시', '부산광역시'), ('서울특별시', '서울특별시'), ('세종특별자치시', '세종특별자치시'), ('울산광역시', '울산광역시'), ('인천광역시', '인천광역시'), ('전라남도', '전라남도'), ('전라북도', '전라북도'), ('제주특별자치도', '제주특별자치도'), ('충청남도', '충청남도'), ('충청북도', '충청북도')], max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=5000)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_users', models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=community.models.ArticleImage.article_image_path)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.article')),
            ],
        ),
    ]
